title: "CRITISEC"

author:
  name: GitHub User
  email: your-email@domain.com

description: > # this means to ignore newlines until "show_excerpts:"
  © HITEC Luxembourg S.A. 2020
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- project.md
- consortium.md
- publications.md
- software.md

# Build settings
theme: minima

plugins:
 - jekyll-seo-tag
